title: kriszti
email: me@kriszt.in
description: Front-end developer with UX and UI experience
baseurl: '' # the subpath of your site, e.g. /blog
url: https://krisztin.github.io
permalink: /blog/:title

# Social
github_username: krisztin
linkedin_username: nkriszti
codepen_username: krisztiiin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
