title: kriszti
email: me@kriszt.in
description: Front-end developer with UX and UI experience
baseurl: '' # the subpath of your site, e.g. /blog
url: https://krisztin.github.io
permalink: /blog/:title

# Social
github_username: krisztin
linkedin_username: nkriszti
codepen_username: krisztiiin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
